<?php

use Illuminate\Database\Seeder;

class CoreUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('core_users')->delete();
        
        \DB::table('core_users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'first_name' => 'Rameshwor',
                'last_name' => 'Maharjan',
                'email' => 'maharjanrams+1@gmail.com',
                'username' => NULL,
                'gender' => NULL,
                'contact_number' => NULL,
                'password' => '$2y$10$Ih31HlWCKG6VnhhHRqOEX.kxnjA4iD2bDQyb9c60DwoQsN5jhoqoy',
                'verified' => 0,
                'email_token' => '11243aef1de80b9f59ef36f23',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-02-16 02:05:27',
                'updated_at' => '2019-02-16 02:05:27',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            1 => 
            array (
                'id' => 10,
                'first_name' => 'Rameshwor',
                'last_name' => 'Maharjan',
                'email' => 'maharjanrams@gmail.com',
                'username' => NULL,
                'gender' => NULL,
                'contact_number' => NULL,
                'password' => '$2y$10$lB9oJAKDc4nqFa9k9MjdmuS.bUUlSQlUbiEoVDEnm1xOOqYGHpKFK',
                'verified' => 1,
                'email_token' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-02-17 11:00:36',
                'updated_at' => '2019-05-10 22:53:20',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            2 => 
            array (
                'id' => 28,
                'first_name' => 'Sudip',
                'last_name' => 'Limbu',
                'email' => 'responsivesudip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '923829823',
                'password' => '$2y$10$nUoA8bnw4xo303Wt69GZYOdiTUGjyJyJco1SY9kZmWexPct2mVW/K',
                'verified' => 1,
                'email_token' => NULL,
                'remember_token' => '2I4VaLSRIvhIkE7QAjwL9nVru6QTAa3qB3kvMp4NC7u2dv237WrjO3QiL8yU',
                'is_active' => 1,
                'profile_pic' => 'https://s3-ap-southeast-2.amazonaws.com/lottery/profile/HIqz4zqfSFrCWgCXNKWIIhQtm2VkjJ.jpeg',
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-02 15:45:39',
                'updated_at' => '2019-05-14 23:47:21',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            3 => 
            array (
                'id' => 29,
                'first_name' => 'Open',
                'last_name' => 'User',
                'email' => 'open_wupbohp_user@tfbnw.net',
                'username' => NULL,
                'gender' => 'female',
                'contact_number' => NULL,
                'password' => '$2y$10$N7HfBHCogWRCKZh4F4nd/egseYdKi4HA.XU9nIQ75fBQVlCezJvcO',
                'verified' => 0,
                'email_token' => 'fdcf9e24',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => 'https://s3-ap-southeast-2.amazonaws.com/lottery/profile/Zj4fUFlvuj0Tawlbkw9DHPTtTz7KPC.jpeg',
                'fb_id' => 121486989032212,
                'device_id' => NULL,
                'created_at' => '2019-05-03 09:29:28',
                'updated_at' => '2019-05-04 10:16:31',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            4 => 
            array (
                'id' => 30,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'testitlsdkf@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'password' => '$2y$10$cIzSsILts/gpg93JDHWwV.Tu.EY7Sm.yjpIKybpXUvw32QWXrCwZq',
                'verified' => 1,
                'email_token' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-04 10:09:59',
                'updated_at' => '2019-05-04 16:07:27',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            5 => 
            array (
                'id' => 31,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responsivesusdfsddip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'password' => '$2y$10$Ee2ODDSQ/SGxhLbaTeZ40OqAP1FT9ed5GuTe29aGmeZh.F0WqBg7K',
                'verified' => 1,
                'email_token' => '9e926bdb',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-04 15:53:55',
                'updated_at' => '2019-05-04 15:53:55',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            6 => 
            array (
                'id' => 32,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responsivesusdfsdsddip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'password' => '$2y$10$pZ15nsi3S3OCjrDyET3JaOO4JxRpYZpyNIMd69YT86OoJW.K7sF/e',
                'verified' => 1,
                'email_token' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-04 15:54:56',
                'updated_at' => '2019-05-04 15:56:12',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            7 => 
            array (
                'id' => 33,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responsivesdsudip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'password' => '$2y$10$MdKZ0KH27CpOLD545F85kukeEZzECLGiEPVNjpP6Fg4G27ex9PDYC',
                'verified' => 0,
                'email_token' => '37f03c09',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-04 15:56:53',
                'updated_at' => '2019-05-04 15:56:53',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            8 => 
            array (
                'id' => 34,
                'first_name' => 'furst',
                'last_name' => 'sdfsd',
                'email' => 'responsivesdsdfsudip@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '29382398238923',
                'password' => '$2y$10$FsClJRrIOXx4N4f1VaSrCeowbY5fJ7rKBargd0lb56gcYDBxOhveK',
                'verified' => 1,
                'email_token' => NULL,
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-04 15:58:10',
                'updated_at' => '2019-05-04 15:58:32',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            9 => 
            array (
                'id' => 35,
                'first_name' => 'Sudip',
                'last_name' => 'Limbu',
                'email' => 'asfsdfasd@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '9823839283',
                'password' => '$2y$10$/WFie1Z2NxmjelTplQaZnuuizIe1l8TDH97sqxT9JiwnMV7ozr/VW',
                'verified' => 0,
                'email_token' => '269d2fc3',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-10 05:17:20',
                'updated_at' => '2019-05-10 05:17:20',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            10 => 
            array (
                'id' => 36,
                'first_name' => 'Sudip',
                'last_name' => 'Limbu',
                'email' => 'asfsdfsdfsasd@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '9823839283',
                'password' => '$2y$10$bM8adoSrqr9WN2ivhrB1b.YO2Gma0AOqXjWXmETWjZcm33OCuWcru',
                'verified' => 0,
                'email_token' => '836402c2',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => 'sddslfk23982323',
                'created_at' => '2019-05-10 05:18:06',
                'updated_at' => '2019-05-10 05:18:06',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
            11 => 
            array (
                'id' => 37,
                'first_name' => 'binay',
                'last_name' => 'awale',
                'email' => 'binay.awale@gmail.com',
                'username' => NULL,
                'gender' => 'male',
                'contact_number' => '0415723914',
                'password' => '$2y$10$1AjnzMvfhpWhk10uGw/b8ec/dNJD5g0Bilh3usmxOpYoTME.s/Y26',
                'verified' => 1,
                'email_token' => 'a4cac484',
                'remember_token' => NULL,
                'is_active' => 1,
                'profile_pic' => NULL,
                'fb_id' => NULL,
                'device_id' => NULL,
                'created_at' => '2019-05-10 22:56:09',
                'updated_at' => '2019-05-10 22:56:09',
                'deleted_at' => NULL,
                'last_login_date' => NULL,
            ),
        ));
        
        
    }
}