version: "3.7"
services:
  app:
    build:
      args:
        D_USER_ID: ${D_USER_ID}
        D_USER: ${D_USER}
        D_GROUP_ID: ${D_GROUP_ID}
        D_GROUP: ${D_GROUP}
      context: ./
      dockerfile: Dockerfile
    image: limvus/lottery
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.datecron.schedule: "@every 60s"
      ofelia.job-exec.datecron.command: "php artisan schedule:run"
    #command: >
    # bash -c "php artisan queue:work"

  queue:
    image: ipunktbs/laravel-queue-worker
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/app

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - lottery_db:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8888:80"

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}

  redis:
    image: redis:alpine
    command:
      - redis-server
      - --appendonly yes
    restart: unless-stopped
    volumes:
      - redis_db:/data
    healthcheck:
      test: redis-cli -h redis -p 6379 ping
      start_period: 1s
      interval: 1s
      timeout: 3s
      retries: 10

  laravel-echo-server:
    image: oanhnn/laravel-echo-server:latest
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - 6001:6001
    volumes:
      - ./:/app
    healthcheck:
      test: /usr/local/bin/health-check
      start_period: 1s
      interval: 1s
      timeout: 3s
      retries: 10

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - nginx
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: projects_default

volumes:
  lottery_db:
  redis_db:
